MODEL:
  ATSS:
    NUM_CLASSES: 8 # Placeholder
  FCOS:
    NUM_CLASSES: 8 # Placeholder
  ROI_BOX_HEAD:
    NUM_CLASSES: 8 # Placeholder
  DYHEAD:
    NUM_CLASSES: 8 # Placeholder
DATASETS:
  TRAIN: ("refexp_val", )
  TEST: ("refexp_val", )

INPUT:
  # MIN_SIZE_TRAIN: 800
  # MAX_SIZE_TRAIN: 1333
  # MIN_SIZE_TEST: 800
  # MAX_SIZE_TEST: 1333
  MIN_SIZE_TRAIN: 224
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 224
  MAX_SIZE_TEST: 224
  FIX_RES: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False

PROMPT:
  PROMPT_DEPTH: 9
  ENABLE: True
  PROMPT_LENGTH: 8
  TYPE: "Mask-VPT-V3"

TEST:
  EVAL_TASK: 'grounding'