MODEL:
  ATSS:
    NUM_CLASSES: 8 # Placeholder
  FCOS:
    NUM_CLASSES: 8 # Placeholder
  ROI_BOX_HEAD:
    NUM_CLASSES: 8 # Placeholder
  DYHEAD:
    NUM_CLASSES: 8 # Placeholder
DATASETS:
  TRAIN: ("refexp_train", )
  TEST: ("refexp_val", "refexp_testA", "refexp_testB")
  FLICKR_GT_TYPE: "separate"

INPUT:
  # MIN_SIZE_TRAIN: 800
  # MAX_SIZE_TRAIN: 1333
  # MIN_SIZE_TEST: 800
  # MAX_SIZE_TEST: 1333
  MIN_SIZE_TRAIN: 224
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 224
  MAX_SIZE_TEST: 224
  FIX_RES: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False

AUGMENT:
  MULT_MIN_SIZE_TRAIN: ()
  FLIP_PROB_TRAIN: 0.0

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER: "ADAMW"
  USE_AUTOSTEP: False

# _C.PROMPT = CN()
# _C.PROMPT.PROMPT_DEPTH = 6
# _C.PROMPT.DIFFUSION = CN()
# _C.PROMPT.DIFFUSION.SAMPLE_DISTANCE = 5
PROMPT:
  PROMPT_DEPTH: 9
  ENABLE: True
  PROMPT_LENGTH: 16
  TYPE: "Mask-VPT-V3"
