MODEL:
  ATSS:
    NUM_CLASSES: 8 # Placeholder
  FCOS:
    NUM_CLASSES: 8 # Placeholder
  ROI_BOX_HEAD:
    NUM_CLASSES: 8 # Placeholder
  DYHEAD:
    NUM_CLASSES: 8 # Placeholder
DATASETS:
  TRAIN: ("refexp_testA", )
  TEST: ("refexp_testA", )

INPUT:
  # MIN_SIZE_TRAIN: 800
  # MAX_SIZE_TRAIN: 1333
  # MIN_SIZE_TEST: 800
  # MAX_SIZE_TEST: 1333
  MIN_SIZE_TRAIN: 224
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 224
  MAX_SIZE_TEST: 224
  FIX_RES: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
PROMPT:
  ENABLE: False